# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-18 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_auto_20161016_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='list.top'),
        ),
    ]
