# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-19 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0008_auto_20161019_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='num',
        ),
        migrations.RemoveField(
            model_name='top',
            name='num',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='list.top'),
        ),
    ]
