# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-20 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0010_auto_20161019_1243'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='category',
            order_with_respect_to=None,
        ),
    ]
